export const todoConstants = {
  // todo add
  TODO_ADD_REQUEST: "TODO_ADD_REQUEST",
  TODO_ADD_SUCCESS: "TODO_ADD_SUCCESS",
  TODO_ADD_FAILED: "TODO_ADD_FAILED",

  // todo update
  TODO_UPDATE_REQUEST: "TODO_UPDATE_REQUEST",
  TODO_UPDATE_SUCCESS: "TODO_UPDATE_SUCCESS",
  TODO_UPDATE_FAILED: "TODO_UPDATE_FAILED",

  // todo delete
  TODO_DELETE_REQUEST: "TODO_DELETE_REQUEST",
  TODO_DELETE_SUCCESS: "TODO_DELETE_SUCCESS",
  TODO_DELETE_FAILED: "TODO_DELETE_FAILED",

  // todo done
  TODO_DONE_REQUEST: "TODO_DONE_REQUEST",
  TODO_DONE_SUCCESS: "TODO_DONE_SUCCESS",
  TODO_DONE_FAILED: "TODO_DONE_FAILED",
};
